# Generated by Django 5.2.7 on 2025-10-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="replied_comment_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the comment that was replied to.",
                max_length=255,
                null=True,
            ),
        ),
    ]
