# Generated by Django 5.2.7 on 2025-10-18 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_tasklog_replied_comment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagramaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instagram_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
