# Generated by Django 5.2.7 on 2025-10-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_instagramaccount_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationrule",
            name="reply_text",
        ),
        migrations.RemoveField(
            model_name="automationrule",
            name="reply_type",
        ),
        migrations.AddField(
            model_name="automationrule",
            name="comment_reply_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="direct_reply_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="send_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="send_direct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="automation.monitoredpost",
            ),
        ),
    ]
