# Generated by Django 5.2.7 on 2025-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0004_remove_automationrule_reply_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="use_ai_reply",
            field=models.BooleanField(default=False),
        ),
    ]
