# Generated by Django 5.2.7 on 2025-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_automationrule_use_ai_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagramaccount",
            name="proxy",
            field=models.CharField(
                blank=True,
                help_text="e.g., http://user:pass@host:port",
                max_length=255,
                null=True,
            ),
        ),
    ]
